apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "onicost-agent.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "onicost-agent.labels" . | nindent 4 }}
automountServiceAccountToken: true
